version: "3.1"
services:

  mysql:
    image: mysql:5.6
    container_name: test-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=app-test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "8004:3306"

  webserver:
    image: nginx:alpine
    container_name: app-test-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8002:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: app-test-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
